#!/bin/sh
#
# "wlanpi-wconsole" postinst script
#

# hostapd is installed with service masked, need to umask 
systemctl unmask hostapd

# stop & disable hostapd & ser2net after installed
# as not needed until we flip modes
systemctl stop hostapd
systemctl stop ser2net

systemctl disable hostapd
systemctl disable ser2net

sed -i 's#CONFFILE="/etc/ser2net.yaml"#CONFFILE="/etc/ser2net.conf"#' /etc/default/ser2net

exit 0